### ISSUE TITLE
Explain the difference with CodiMD

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/hedgedoc_ynh#1]
After all forks and renaming on HedgeDoc side, I think it's confusing for a lot of people and hard to know what is what.
So I think it's important to explain in the readme (and maybe package description, as most users will only see that in Yunohost interface) that this was CodiMD package and so on.
Something similar to https://github.com/YunoHost-Apps/codimd_ynh/pull/54 
In package description, maybe only "Fork of CodiMD" ?

**Comment by mrdrogdrog** [comment]
I would prefer to link https://hedgedoc.org/history/

**Comment by lapineige** [comment]
Compared to what option ?

You made me realise we did not even include that link in the readme… I'll fix that

**Comment by mrdrogdrog** [comment]
<del>prefer</del>

**Comment by lapineige** [comment]
https://github.com/YunoHost-Apps/codimd_ynh/pull/56

**Comment by ericgaspar** [comment]
Closing with #18
