### ISSUE TITLE
Don't build HedgeDoc on the target system

### ISSUE THREAD

**Issue by mrdrogdrog** [YunoHost-Apps/hedgedoc_ynh#15]
It seems like you still build HedgeDog on the target system. Since version 1.7.0 there is a prebundled version. You should prefer this one, so systems with less RAM can install HedgeDoc as well.

**Comment by lapineige** [comment]
ping #7, I believed it has been fixed here https://github.com/YunoHost-Apps/hedgedoc_ynh/issues/7#issuecomment-753478236

**Comment by mrdrogdrog** [comment]
My fault. I misinterpreted the config files. 😅 Sry to bother you.

**Comment by lapineige** [comment]
No worries :)
