### ISSUE TITLE
Can't install on raspberry pi4

### ISSUE THREAD

**Issue by noccio** [YunoHost-Apps/hedgedoc_ynh#2]
I tried to install hedgedoc on my raspberry pi4 with yunohost stable but I get the same error for CodiMD (https://github.com/YunoHost-Apps/codimd_ynh/issues/53 and https://forum.yunohost.org/t/codimd-cant-install-on-raspberry/13358).

In the install process I get the error:

    Error verifying phantomjs, continuing Error: Command failed: /usr/bin/phantomjs --version

and

    qt.qpa.screen: QXcbConnection: Could not connect to display
    Could not connect to any X display

I tried to install directly phantomjs but nothing changed.

Full log at https://paste.yunohost.org/raw/hupowarapi

**Comment by ericgaspar** [comment]
Hello @noccio Thanks for the bug report.
For now, HedgeDoc repository installs the same package as CodiMD so logically you get the same error ...
The next HedgeDoc version: 1.7.0 is still in beta testing. You can nevertheless try to install it and report back if the problem persists ...

`sudo yunohost app install https://github.com/YunoHost-Apps/hedgedoc_ynh/tree/1.7.0`

**Comment by noccio** [comment]
The testing version installs normally!
Thanks a lot!
