### ISSUE TITLE
Fails to upgrade from 1.9.4~ynh1 to 1.9.6~ynh2

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost-Apps/hedgedoc_ynh#53]
I tried to upgrade hedgedoc today and it failed with some weird conflicts. [Full log](https://paste.yunohost.org/raw/silobokoji)

**Comment by ericgaspar** [comment]
Please see this forum thread: https://forum.yunohost.org/t/hedgedoc-update-fails-1-9-5-1-9-6/22098/7

**Comment by selfhoster1312** [comment]
Sorry i didn't search the closed issues. Can we maybe perform these steps automatically in the upgrade script?

**Comment by ericgaspar** [comment]
should be fixed. Open a new issue if it's not.
