### ISSUE TITLE
Allow users to choose pad URLs

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost-Apps/hedgedoc_ynh#54]
This is a great feature of etherpad making it popular, that users can choose the URL of the pad... by just going to pad.example.com/p/myurl. Now hedgedoc has support for this [in config](https://docs.hedgedoc.org/configuration/#users-and-privileges) via allowFreeURL and requireFreeURLAuthentication.

The latter is used to prevent bots from auto-creating pads with names to well-known paths like /admin /acme-challenge etc.

**Comment by ericgaspar** [comment]
Setting added to config panel (`false` by default). https://github.com/YunoHost-Apps/hedgedoc_ynh/commit/de36e0d8974ba1dd6aa70c33a1c998be7ff521dd
