### ISSUE TITLE
Upgrade from 1.9.5~ynh1 to 1.9.6~ynh2 fails

### ISSUE THREAD

**Issue by pagiraud** [YunoHost-Apps/hedgedoc_ynh#55]
Hi,
Full log here: https://paste.yunohost.org/raw/iqayujevem

Seems very similar to #53

**Comment by ericgaspar** [comment]
Please see this forum thread: https://forum.yunohost.org/t/hedgedoc-update-fails-1-9-5-1-9-6/22098/7

**Comment by pagiraud** [comment]
Thanks, I made progress. Now I encounter another error: 
Full log: https://paste.yunohost.org/raw/etejecibog

Now it seems very similar to #52 

Then, I could manually install chromium on the server but… why is that even a dependency? I had a look into Hedgedoc Github repo and I can’t find any reference to such a dependency or issues related to chromium.

This line from the log is intriguing : 

    Warning: ERROR: Failed to set up Chromium r1045629! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

Maybe just adding this variable to the script would resolve the issue…

**Comment by ericgaspar** [comment]
should be fixed. Open a new issue if it's not.
