### ISSUE TITLE
Plantuml doesn't work by default

### ISSUE THREAD

**Issue by remcoboerma** [YunoHost-Apps/hedgedoc_ynh#59]
### Describe the bug

Given that CodiMD supports plantuml out of the box (also on yunohost), i'd expect hedgedoc to do the same. 
There seems to be support, based on some environment variable, but i can't figure out where to put that. 

### Context

- Hardware: *old server at home*
- YunoHost version:  11.1.11.2 (stable).
- I have access to my server: Through SSH, through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Current version: 1.9.6~ynh2

### Steps to reproduce

new install of the application on the root of a free domain, using web admin
reinstall using `sudo yunohost app install  hedgedoc --label HedgeDoc -a "domain=..." ` and answering `/` for the path and `no` for public access. 

### Expected behavior

After entering a codeblock with `plantuml` it would have to include plantuml output. Instead it shows the code in preformatted text block. 

### Logs
None.

**Comment by remcoboerma** [comment]
In the CodiMD-ynh repo there is no mention of `plantuml` so it's in those settings

**Comment by ericgaspar** [comment]
I don't know if HedgeDoc supports `plantuml` as CodiMD does, but you can try the diagram syntax as shown https://demo.hedgedoc.org/s/features#Diagrams

**Comment by ericgaspar** [comment]
Plantuml will apparently be supported in HedgeDoc v2 https://github.com/hedgedoc/hedgedoc/issues/3250
