### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by a2bb892** [YunoHost-Apps/hedgedoc_ynh#7]
I tried installing HedgeDoc, but ran into an error.

It looks like it's an out of memory error, here's a piece of the stacktrace:

> 2020-12-27 20:34:07,830: DEBUG - <--- JS stacktrace --->
> 2020-12-27 20:34:07,830: DEBUG - 
> 2020-12-27 20:34:07,830: DEBUG - FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 2020-12-27 20:34:07,830: DEBUG -  1: 0xa04200 node::Abort() [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,830: DEBUG -  2: 0x94e4e9 node::FatalError(char const*, char const*) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,830: DEBUG -  3: 0xb7860e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  4: 0xb78987 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  5: 0xd33215  [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  6: 0xd33d9f  [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  7: 0xd41e2b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  8: 0xd459ec v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG -  9: 0xd140cb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,831: DEBUG - 10: 0x105a06f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,832: DEBUG - 11: 0x1400039  [/opt/node_n/n/versions/node/14.15.3/bin/node]
> 2020-12-27 20:34:07,832: DEBUG - Aborted
> 2020-12-27 20:34:07,932: DEBUG - error Command failed with exit code 134.
> 2020-12-27 20:34:07,933: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 2020-12-27 20:34:07,933: DEBUG - + ynh_exit_properly
> 2020-12-27 20:34:07,933: DEBUG - + local exit_code=134
> 2020-12-27 20:34:07,934: DEBUG - + '[' 134 -eq 0 ']'
> 2020-12-27 20:34:07,934: DEBUG - + trap '' EXIT
> 2020-12-27 20:34:07,934: DEBUG - + set +o errexit
> 2020-12-27 20:34:07,934: DEBUG - + set +o nounset
> 2020-12-27 20:34:07,935: DEBUG - + sleep 0.5
> 2020-12-27 20:34:08,436: DEBUG - + type -t ynh_clean_setup
> 2020-12-27 20:34:08,437: DEBUG - + ynh_clean_setup
> 2020-12-27 20:34:08,437: DEBUG - + ynh_clean_check_starting
> 2020-12-27 20:34:08,437: DEBUG - + '[' -n '' ']'
> 2020-12-27 20:34:08,437: DEBUG - + '[' -n '' ']'
> 2020-12-27 20:34:08,438: DEBUG - + exit 1
> 2020-12-27 20:34:08,627: ERROR - Could not install hedgedoc: An error occurred inside the app installation script
> 

I'm on a VPS with 1 GB of RAM.

According to the YunoHost documentation, 1 GB of RAM should be enough:
> 512 MB RAM (recommended : 1 GB in order to run all the services and apps properly)
[https://yunohost.org/#/hardware](https://yunohost.org/#/hardware)

But it looks like it's possible that HedgeDoc could use 2 GB of RAM (not sure if the YunoHost version does this)?:
> For building the HedgeDoc frontend you need a machine with at least 2 GB RAM. 
[https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md](https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md)

I can try upgrading the RAM, but before I do is there anything I can try to get it to install with 1 GB of RAM?

YunoHost 4.0.8.3 running on a VPS
Full logs: https://paste.yunohost.org/raw/urayaqoqun

**Comment by ericgaspar** [comment]
HedgeDoc needs a lot of RAM to build (up to 3.5 GB ...). It was the same for CodiMD and I guess those needs haven't changed for HedgeDoc ...

**Comment by lapineige** [comment]
If no significant optimization can come from HedgeDoc, maybe we should prepare some prebuilt packages ?
More than 3Go of ram is a lot for such a small software that could be used with very light servers, and probably most of Yunohost users have less than that.

By the way I did install it on a server with 3GB of RAM (with some swap, I don't know if it used it).

**Comment by a2bb892** [comment]
Thanks for the replying and the info, @ericgaspar @lapineige. I think I'll hold off on upgrading my VPS for now, nonetheless I appreciate the info! :smile:

**Comment by TheNomad11** [comment]
Thanks for the info about RAM, my VPS (with 4GB RAM and 1.5GB already in use) crashed during the installation. I did not have these issues with CodiMD before. This requirement makes this app less useful for most of us, I agree here with @lapineige

**Comment by lapineige** [comment]
It did work for me on a 3GB server with already 1.5GB used… but I had some swap.

**Comment by TheNomad11** [comment]
I did not have swap, no need so far as 4GB are more than enough normally, so that might be the reason for why it did not work for me

**Comment by ericgaspar** [comment]
Since version 1.7, HedgeDoc provides a tarball file including prebuid fontend. I haven't tested if this will help small setups to buid HedgeDoc... tests will be appreciated by those using Raspberry Pi.  

`sudo yunohost app install https://github.com/YunoHost-Apps/hedgedoc_ynh/tree/tarball-release`

**Comment by lapineige** [comment]
That's great !
Let's see if #9 fixes this issue :+1: 

My test on a Raspberry Pi 4: it started with a load around 1.5 and memory usage around 520MB, and the peak was around a load of ~6 (but that was before building, during building it was around 4, with 1 core at 100%) and 930MB of RAM in use… which is fairly reasonable.

It took ~20min.

**Comment by lapineige** [comment]
#9 Merged, maybe we can close this issue unless the problem happens again ?

**Comment by a2bb892** [comment]
I just tried installing (with no upgrades to my VPS), and it's working, thanks everyone for helping with this! :smile: :tada:

**Comment by ericgaspar** [comment]
Closing. Do not hesitate to reopen if necessary
