### ISSUE TITLE
Update HedgeDoc (hedgedoc) from 1.9.9~ynh3 to 1.10.0~ynh1 failed

### ISSUE THREAD

**Issue by rmueck** [YunoHost-Apps/hedgedoc_ynh#79]
### Describe the bug

Update failed!

See: [logs](https://paste.yunohost.org/raw/aguxohezev)
### Context

- Hardware: VPS
- YunoHost version: 11.2.30 (stable).
- I have access to my server: Through SSH

### Steps to reproduce
Initiate update

### Expected behavior
Update is successful

### Logs
See: [logs](https://paste.yunohost.org/raw/aguxohezev)

**Comment by ericgaspar** [comment]
We are waiting for version 1.10.0 to come back (a bug was found upstream and the version was withdrawn). reverting to 1.9.9
